# Generated by Django 6.1.1 on 2026-09-14 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicacion', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensajecomunicacion',
            name='fecha_lectura',
        ),
        migrations.RemoveField(
            model_name='mensajecomunicacion',
            name='leido',
        ),
        migrations.CreateModel(
            name='LecturaMensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leido', models.BooleanField(default=False)),
                ('fecha_hora_lectura', models.DateTimeField(blank=True, null=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registro_lecturas', to=settings.AUTH_USER_MODEL)),
                ('mensaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='comunicacion.mensajecomunicacion')),
            ],
            options={
                'verbose_name': 'Registro de Lectura',
                'verbose_name_plural': 'Registros de Lecturas',
                'unique_together': {('mensaje', 'destinatario')},
            },
        ),
    ]
