# Generated by Django 6.1.1 on 2026-09-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['nivel', 'letra'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.RemoveField(
            model_name='asistencia',
            name='porcentaje_asistencia_actual',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='grado_curso',
        ),
        migrations.AddField(
            model_name='curso',
            name='letra',
            field=models.CharField(default='A', max_length=1, verbose_name='Letra'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='nivel',
            field=models.CharField(default='1ero Basico', max_length=50, verbose_name='Nivel'),
            preserve_default=False,
        ),
    ]
